controller_names:
  - scaled_joint_trajectory_controller
  - linear_slider_controller

scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - $(var prefix)joint1

linear_slider_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - $(var prefix)joint1
