# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    linear_slider_hardware_interface:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

linear_slider_hardware_interface:
  ros__parameters:
    joint: joint1
    command_interfaces:
      - position
      - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
      # - effort