controller_manager:
  ros__parameters:
    update_rate: 10 # hz

    joint_state_broacaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Make sure this matches up with the URDF
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_platform_prismatic_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # defaults to 50
    action_monitor_rate: 20.0 # defaults to 20

    allow_partial_joints_goal: false # defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # defaults to 0.0 (start immediately)
      
    allow_nonzero_velocity_at_trajectory_end: false