controller_manager:
  ros__parameters:
    update_rate: 2000 # hz

    linear_slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # TODO: Therefore if the hardware provides only acceleration or velocity states they have to be integrated in the hardware-interface implementation of velocity and position to use these controllers.

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

linear_slider_controller:
  ros__parameters:
    joints:
      - $(var prefix)joint1

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    gains: # required for velocity interface
      $(var prefix)joint1:
        ff_velocity_scale: 1.0
        p: 6.0
        i: 2.0
        d: 2.0
        # p: 100.0
        # i: 2.0
        # d: 5.0
        # i_clamp: 1.0

    state_publish_rate: 100.0 # defaults to 50
    action_monitor_rate: 50.0 # defaults to 20

    allow_partial_joints_goal: false # defaults to false
    # stop_trajectory_duration: 0.1
    constraints:
      goal_time: 10.0 # defaults to 0.0 (start immediately)
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      $(var prefix)joint1:
        goal: 0.05 # position tolerace (m)
        # trajectory: 1.0

    allow_nonzero_velocity_at_trajectory_end: false
