publisher_joint_trajectory_controller:
    ros__parameters:
        controller_name: "joint_trajectory_controller"
        wait_sec_between_publish: 6
        repeat_the_same_goal: 1 # useful to simulate continuous inputs

        goal_time_from_start: 3.0

        goal_names: ["pos1", "pos2", "pos3"]
        # Positions
        pos1:
            positions: [0.0] # center
        pos2:
            positions: [0.3] # to the right (away from motor)
        pos3:
            positions: [-0.3] # to the left (toward motor)

        joints:
            - joint1
