publisher_velocity_controller:
  ros__parameters:
    controller_name: "velocity_controller"
    wait_sec_between_publish: 0.1
    repeat_the_same_goal: 1

    goal_time_from_start: 3.0

    goal_names: ["vel0", "vel1"]

    vel0:
      velocities: [0.05]
    vel1:
      velocities: [-0.05]

    joints:
      - joint1