# MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
controller_names:
  - linear_slider_controller
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller

linear_slider_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - $(var prefix)joint1

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - $(var tf_prefix)shoulder_pan_joint
    - $(var tf_prefix)shoulder_lift_joint
    - $(var tf_prefix)elbow_joint
    - $(var tf_prefix)wrist_1_joint
    - $(var tf_prefix)wrist_2_joint
    - $(var tf_prefix)wrist_3_joint

scaled_joint_trajectory_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - $(var tf_prefix)shoulder_pan_joint
    - $(var tf_prefix)shoulder_lift_joint
    - $(var tf_prefix)elbow_joint
    - $(var tf_prefix)wrist_1_joint
    - $(var tf_prefix)wrist_2_joint
    - $(var tf_prefix)wrist_3_joint
